// src/routes/_authed.component.vue
<script lang="ts" setup>
import { useQuery } from "@tanstack/vue-query";
import { Outlet } from "@tanstack/vue-router";
import NavBar from "@/components/header/index.vue";
import { ServerSessionQueryOptions } from "../lib/db/query.functions";

const { data } = useQuery(() => ServerSessionQueryOptions());
</script>

<template>
  <div class="mx-6">
    <NavBar :user="data?.user" />

    <main v-if="data?.user?.name" class="mb-6" id="content">
      <Outlet />
    </main>

    <h1 v-else>Not Logged In</h1>
  </div>
</template>

// src/routes/_authed.tsx
import { ServerSessionQueryOptions } from "@db/query.functions";
import { useQuery } from "@tanstack/vue-query";
import { createFileRoute } from "@tanstack/vue-router";
import { Outlet } from "@tanstack/vue-router";
import NavBar from "@/components/header/index.vue";

export const Route = createFileRoute("/_authed")({
  component: RootComponent,
  beforeLoad: async ({ context }) => {
    await context.queryClient.prefetchQuery(ServerSessionQueryOptions());
  },
});

function RootComponent() {
  const { data } = useQuery(() => ServerSessionQueryOptions());

  return (
    <section>
      <NavBar user={data?.value?.user} />

      {data?.value?.user?.name ? <Outlet /> : <h1>Not Logged In</h1>}
    </section>
  );
}
